add card4
krishsharma0413/DiscordLevelingCard pull request #12
Opened 2023-06-16 16:36 UTC by LevaniVashadze

2023-06-16 16:37 UTC, LevaniVashadze commented
the images in the readme act as links for now since the image links are not yet working, but will work when merged

2023-06-16 19:19 UTC, krishsharma0413 requested changes

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/assets/card4.png
there is a small white dot on the top left side of the bar.

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/discord_card.py
> +        with Image.open(path + "/assets/card4.png").convert(
if the assets already has username, exp, exp bar premade then their is no scope for background image in future as well

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/discord_card.py
> +                def mask_circle_transparent(pil_img, blur_radius, offset=0):
make this function as static method in the class itself and don't include it in documention. Each time the `card4` function would be called, the function would get redefined which isn't ideal

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/discord_card.py
> +                def mask_circle_transparent(pil_img, blur_radius, offset=0):
i think using the mask circle would be better than this since this adds blur to the avatar

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/discord_card.py
> +                def roundify(im, rad):
static method needed

2023-06-16 19:19 UTC, krishsharma0413 commented on DiscordLevelingCard/tester.py
> +        """test card1 with this method
card1 should be card4

2023-06-16 19:19 UTC, krishsharma0413 commented on README.md
> +`card4` design from Ogiroid bot
whats ogiroid bot

2023-06-17 07:02 UTC, LevaniVashadze commented on README.md
> +`card4` design from Ogiroid bot
Its the bot where this design was first implemented, I can remove the mention of it

2023-06-17 07:03 UTC, LevaniVashadze commented on DiscordLevelingCard/discord_card.py
> +        with Image.open(path + "/assets/card4.png").convert(
Yeah, I need to redo that part, since I just copied over the code

2023-06-17 08:20 UTC, LevaniVashadze commented on DiscordLevelingCard/discord_card.py
> +        with Image.open(path + "/assets/card4.png").convert(
fixed

2023-06-17 08:20 UTC, LevaniVashadze commented on DiscordLevelingCard/discord_card.py
> +                def mask_circle_transparent(pil_img, blur_radius, offset=0):
done

2023-06-17 08:20 UTC, LevaniVashadze commented on DiscordLevelingCard/tester.py
> +        """test card1 with this method
fixed

2023-06-17 08:20 UTC, LevaniVashadze commented on DiscordLevelingCard/discord_card.py
> +                def roundify(im, rad):
done

2023-06-17 08:25 UTC, LevaniVashadze commented on README.md
> +`card4` design from Ogiroid bot
made it more clear

2023-07-01 19:35 UTC, LevaniVashadze commented
@krishsharma0413 can you re-review

2023-07-02 07:35 UTC, krishsharma0413 commented
It's better to not include this PR since similar design is easily possible with sandbox and more features to add custom texts and more images are getting included in sandbox as well. It would make this unusable at all

2023-07-02 07:35 UTC, closed without merging